version: '3.6'

services:

  nginx:
    container_name: ${PROJECT_NAME}-nginx
    build:
      context: .ci/docker/nginx
      args:
        TIMEZONE: ${TIMEZONE}
        VERSION: ${NGINX_VERSION}
    volumes:
      - ./:/var/www/html/
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - app
    ports:
      - ${NGINX_PORT}:80
    networks:
      - main

  app:
    container_name: ${PROJECT_NAME}-app
    build:
      context: .ci/docker/php-fpm
      args:
        TIMEZONE: ${TIMEZONE}
        VERSION: ${PHP_FPM_VERSION}
        COMPOSER_VERSION: ${COMPOSER_VERSION}
        XDEBUG_REMOTE_HOST: ${XDEBUG_REMOTE_HOST}
        XDEBUG_REMOTE_PORT: ${XDEBUG_REMOTE_PORT}
        XDEBUG_IDEKEY: ${XDEBUG_IDEKEY}
        GID: ${GID}
        UID: ${UID}
    volumes:
      - ./:/var/www/html:cached
      - ./.ci/docker/supervisor/:/etc/supervisor.d/
      - ./logs/supervisord/:/var/supervisord/logs
    depends_on:
      - postgres
    networks:
      - main
    ports:
      - 9001:9001

  postgres:
    container_name: ${PROJECT_NAME}-postgres
    build:
      context: .ci/docker/postgres
      args:
        VERSION: ${POSTGRES_VERSION}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_MULTIPLE_DATABASES: ${IDENTITY_DB}, ${DIGEST_DB}
    volumes:
      - pgdata:/var/lib/postgresql
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - main

networks:
  main:
    driver: bridge

volumes:
  pgdata: